name: Manual Pipeline Check

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate changelog entry
        env:
          BRANCH_LIST: ${{ github.ref_name }}
        run: |
          python scripts/changelog/generate_changelog.py --branches "$BRANCH_LIST" --clear-description-file

      - name: Run tests
        env:
          TG_TOKEN: dummy-token
        run: pytest
